### PR TITLE
rewrote urls in css

### PR DESCRIPTION
**Pull request by sergeospb**
@import url(reset.css);
url(/img/site/template/marker.png)
etc

### CODE REVIEW

**Comment by anandology** [comment]
The wayback part is only added for testing the liveweb, it was never meant for real use. But happy to support it if you using it.

What are you using it for? I'm curious to know.

**Comment by sergeospb** [comment]
I planning to use it as web proxy.

**Comment by anandology** [comment]
This doesn't support POST requests. I don't think you can use this as a
real proxy server.

On Tue, Mar 26, 2013 at 9:19 AM, sergeospb notifications@github.com wrote:

> I planning to use it as web proxy.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/internetarchive/liveweb/pull/46#issuecomment-15439563
> .

## 

Anand
http://anandology.com/

**Comment by sergeospb** [comment]
Yes, I understand, I need just GET method now.

**Pull request merged**
